# Build stage
FROM node:18 as build

# Set working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the frontend code
COPY . .

# Set build arguments
ARG REACT_APP_LOOKER_HOST
ARG REACT_APP_LOOKER_API_URL
ARG REACT_APP_LOOKER_PROXY_URL
ARG REACT_APP_LOOKER_DASHBOARD_1
ARG REACT_APP_LOOKER_DASHBOARD_TAB_1
ARG REACT_APP_LOOKER_DASHBOARD_TAB_2
ARG REACT_APP_LOOKER_LOOKS_TAB_1
ARG REACT_APP_LOOKER_LOOKS_TAB_2
ARG REACT_APP_LOOKER_LOOKS_TAB_3
ARG REACT_APP_SINGLE_CARDS
ARG REACT_APP_TIMESERIES
ARG REACT_APP_LOOKER_EXPLORE

# Set environment variables
ENV REACT_APP_LOOKER_HOST=$REACT_APP_LOOKER_HOST
ENV REACT_APP_LOOKER_API_URL=$REACT_APP_LOOKER_API_URL
ENV REACT_APP_LOOKER_PROXY_URL=$REACT_APP_LOOKER_PROXY_URL
ENV REACT_APP_LOOKER_DASHBOARD_1=$REACT_APP_LOOKER_DASHBOARD_1
ENV REACT_APP_LOOKER_DASHBOARD_TAB_1=$REACT_APP_LOOKER_DASHBOARD_TAB_1
ENV REACT_APP_LOOKER_DASHBOARD_TAB_2=$REACT_APP_LOOKER_DASHBOARD_TAB_2
ENV REACT_APP_LOOKER_LOOKS_TAB_1=$REACT_APP_LOOKER_LOOKS_TAB_1
ENV REACT_APP_LOOKER_LOOKS_TAB_2=$REACT_APP_LOOKER_LOOKS_TAB_2
ENV REACT_APP_LOOKER_LOOKS_TAB_3=$REACT_APP_LOOKER_LOOKS_TAB_3
ENV REACT_APP_SINGLE_CARDS=$REACT_APP_SINGLE_CARDS
ENV REACT_APP_TIMESERIES=$REACT_APP_TIMESERIES
ENV REACT_APP_LOOKER_EXPLORE=$REACT_APP_LOOKER_EXPLORE

# Build the React app
RUN npm run build

# Production stage
FROM node:18-slim

WORKDIR /app

# Copy package.json and package-lock.json for the server
COPY server/package*.json ./

# Install production dependencies
RUN npm install --only=production

# Copy the built React app from the build stage
COPY --from=build /app/build ./build

# Copy the server code
COPY server ./server

# Expose the port the app runs on
EXPOSE 8000

# Set the command to run the app
CMD ["node", "server/app.js"]